---
name: ruby-app

releases:
- name: ruby-app-release
  version: latest

stemcells:
- alias: default
  os: "ubuntu-bionic"
  version: "1.204"

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: ruby-app
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: rubyweb
    release: ruby-app-release
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
